#' Cox Lasso Model Implementation
#' 
#' @description 
#' Implements Cox Lasso regression using the glmnet package with cross-validation
#' for optimal lambda parameter selection. This serves as a baseline method for
#' comparison with TransCox models.
#' 

library(glmnet)
library(survival)

#' Train Cox Lasso Model
#' 
#' @description
#' Trains a Cox proportional hazards model with Lasso (L1) regularization using
#' cross-validation to select the optimal regularization parameter.
#' 
#' @param train_data A data.frame containing the training dataset with survival
#'   times, event status, and covariates.
#' @param cov_names A character vector specifying the names of covariates to be
#'   included in the model.
#' @param alpha Numeric. Elastic Net mixing parameter. 1 = Lasso (L1 penalty),
#'   0 = Ridge (L2 penalty). Default is 1.
#' @param nfolds Integer. Number of folds for cross-validation. Default is 10.
#' @param lambda_seq Numeric vector. Sequence of lambda values for regularization.
#'   If NULL, will be automatically generated by glmnet. Default is NULL.
#' @param verbose Logical. Whether to display training progress information.
#'   Default is TRUE.
#' 
#' @return A list containing the following components:
#' \describe{
#'   \item{model}{The fitted glmnet model object}
#'   \item{cv_model}{The cross-validation results}
#'   \item{lambda_min}{The lambda value that minimizes cross-validation error}
#'   \item{lambda_1se}{The lambda value within 1 standard error of minimum}
#'   \item{coefficients}{The estimated coefficients at lambda_min}
#'   \item{active_vars}{Names of variables with non-zero coefficients}
#' }
#' 
#' @examples
#' \dontrun{
#' # Generate example data
#' data <- generate_sparse_survival_data(n_main = 100, p = 50)
#' 
#' # Train Cox Lasso model
#' lasso_model <- train_cox_lasso(
#'   train_data = data$prim_data,
#'   cov_names = paste0("X", 1:50)
#' )
#' 
#' # View results
#' print(lasso_model$lambda_min)
#' print(lasso_model$active_vars)
#' }
#' 
#' @export
train_cox_lasso <- function(train_data, 
                           cov_names, 
                           alpha = 1, 
                           nfolds = 10, 
                           lambda_seq = NULL,
                           verbose = TRUE) {
    
    if (verbose) cat("开始训练Cox Lasso模型...\n")
    
    # 准备数据
    X <- as.matrix(train_data[, cov_names])
    # 确保事件状态编码正确：status=2表示事件，status=1表示删失
    # Surv函数期望0/1编码，所以转换为status==2
    y <- Surv(train_data$time, train_data$status == 2)
    
    # 训练模型
    if (verbose) {
        cat("训练样本数:", nrow(X), "\n")
        cat("特征数:", ncol(X), "\n")
        cat("事件数:", sum(train_data$status == 2), "\n")
    }
    
    # 生成lambda序列
    if (is.null(lambda_seq)) {
        lambda_seq <- glmnet::glmnet(X, y, 
                                   family = "cox", alpha = alpha)$lambda
        if (verbose) cat("自动生成", length(lambda_seq), "个lambda值\n")
    }
    
    # 交叉验证
    cv_fit <- glmnet::cv.glmnet(X, y,
                              family = "cox", alpha = alpha, lambda = lambda_seq,
                              nfolds = nfolds, type.measure = "C")
    
    # 选择最优lambda
    best_lambda <- cv_fit$lambda.min
    best_lambda_1se <- cv_fit$lambda.1se
    
    if (verbose) {
        cat("最优lambda (min):", round(best_lambda, 6), "\n")
        cat("最优lambda (1se):", round(best_lambda_1se, 6), "\n")
        cat("对应的C-index (min):", round(max(cv_fit$cvm), 4), "\n")
    }
    
    # 使用最优lambda拟合最终模型
    final_fit <- glmnet(X, y, 
                       family = "cox", 
                       alpha = alpha,
                       lambda = best_lambda)
    
    # 提取系数
    coefficients <- as.vector(coef(final_fit))
    names(coefficients) <- cov_names
    
    # 计算非零系数数量
    n_nonzero <- sum(abs(coefficients) > 1e-8)
    
    if (verbose) {
        cat("非零系数数量:", n_nonzero, "/", length(coefficients), "\n")
        cat("稀疏度:", round((length(coefficients) - n_nonzero) / length(coefficients) * 100, 1), "%\n")
    }
    
    return(list(
        model = final_fit,
        cv_model = cv_fit,
        coefficients = coefficients,
        best_lambda = best_lambda,
        best_lambda_1se = best_lambda_1se,
        n_nonzero = n_nonzero,
        training_info = list(
            n_samples = nrow(X),
            n_features = ncol(X),
            n_events = sum(train_data$status == 2),
            alpha = alpha,
            nfolds = nfolds
        )
    ))
}

#' 使用Cox Lasso模型进行预测
#' 
#' @param model_fit 训练好的Cox Lasso模型
#' @param test_data 测试数据
#' @param cov_names 协变量名称
#' @param use_1se 是否使用lambda.1se而不是lambda.min
#' @return 预测的风险分数
#' @export
predict_cox_lasso <- function(model_fit, test_data, cov_names, use_1se = FALSE) {
    
    # 准备测试数据
    X_test <- as.matrix(test_data[, cov_names])
    
    # 选择lambda
    lambda_use <- if (use_1se) model_fit$best_lambda_1se else model_fit$best_lambda
    
    # 预测线性预测子（风险分数）
    predicted_risk <- predict(model_fit$model, 
                             newx = X_test, 
                             s = lambda_use, 
                             type = "link")
    
    return(as.vector(predicted_risk))
}

#' 评估Cox Lasso模型性能
#' 
#' @param model_fit 训练好的Cox Lasso模型
#' @param test_data 测试数据
#' @param cov_names 协变量名称
#' @param true_beta 真实的回归系数（如果有的话）
#' @param verbose 是否输出详细信息
#' @return 评估结果列表
#' @export
evaluate_cox_lasso <- function(model_fit, test_data, cov_names, true_beta = NULL, verbose = TRUE) {
    
    # Cox Lasso模型评估
    
    # 预测风险分数
    predicted_risk <- predict_cox_lasso(model_fit, test_data, cov_names)
    
    # 加载评估函数
    if (!exists("comprehensive_evaluation")) {
        source("R/evaluation_metrics.R")
    }
    
    # 综合评估
    if (!is.null(true_beta)) {
        evaluation_results <- comprehensive_evaluation(
            predicted_risk = predicted_risk,
            estimated_beta = model_fit$coefficients,
            test_data = test_data,
            true_beta = true_beta
        )
    } else {
        # 只计算预测性能，不计算参数准确性
        cindex <- calculate_cindex(predicted_risk, test_data$time, test_data$status)
        evaluation_results <- list(
            cindex = cindex,
            summary = list(cindex = round(cindex, 4))
        )
    }
    
    if (verbose) {
        cat("C-index:", round(evaluation_results$cindex, 4), "\n")
        cat("非零系数数量:", model_fit$n_nonzero, "\n")
        
        if (!is.null(evaluation_results$parameter_accuracy)) {
            cat("参数相关性:", round(evaluation_results$parameter_accuracy$correlation, 4), "\n")
            cat("F1分数:", round(evaluation_results$parameter_accuracy$f1_score, 4), "\n")
            cat("精确率:", round(evaluation_results$parameter_accuracy$precision, 4), "\n")
            cat("召回率:", round(evaluation_results$parameter_accuracy$recall, 4), "\n")
        }
    }
    
    # 添加模型特定信息
    evaluation_results$model_info <- list(
        method = "Cox Lasso",
        best_lambda = model_fit$best_lambda,
        n_nonzero = model_fit$n_nonzero,
        training_samples = model_fit$training_info$n_samples
    )
    
    evaluation_results$predicted_risk <- predicted_risk
    
    return(evaluation_results)
}

#' 可视化Cox Lasso模型结果
#' 
#' @param model_fit 训练好的Cox Lasso模型
#' @param true_beta 真实系数（可选）
#' @param top_features 显示前几个重要特征
#' @export
plot_cox_lasso_results <- function(model_fit, true_beta = NULL, top_features = 20) {
    
    # 设置图形参数
    par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))
    
    # 1. 交叉验证曲线
    plot(model_fit$cv_model, main = "Cox Lasso交叉验证")
    abline(v = log(model_fit$best_lambda), col = "red", lty = 2)
    
    # 2. 系数路径
    plot(model_fit$cv_model$glmnet.fit, xvar = "lambda", main = "系数路径")
    abline(v = log(model_fit$best_lambda), col = "red", lty = 2)
    
    # 3. 系数条形图
    coefs <- model_fit$coefficients
    nonzero_idx <- which(abs(coefs) > 1e-8)
    
    if (length(nonzero_idx) > 0) {
        # 选择显示的特征
        if (length(nonzero_idx) > top_features) {
            # 按绝对值大小排序，选择前top_features个
            sorted_idx <- nonzero_idx[order(abs(coefs[nonzero_idx]), decreasing = TRUE)]
            show_idx <- sorted_idx[1:top_features]
        } else {
            show_idx <- nonzero_idx
        }
        
        coefs_show <- coefs[show_idx]
        names_show <- names(coefs_show)
        
        # 条形图
        barplot(coefs_show, 
                main = paste("非零系数 (前", length(show_idx), "个)"),
                las = 2, 
                cex.names = 0.8,
                col = ifelse(coefs_show > 0, "red", "blue"))
        abline(h = 0, lty = 2)
    }
    
    # 4. 真实vs估计系数对比（如果有真实值）
    if (!is.null(true_beta)) {
        plot(true_beta, model_fit$coefficients,
             xlab = "真实系数", ylab = "估计系数",
             main = "真实 vs 估计系数",
             pch = 16, col = rgb(0, 0, 1, 0.6))
        abline(0, 1, col = "red", lty = 2)
        
        # 添加相关系数
        cor_val <- cor(true_beta, model_fit$coefficients)
        text(min(true_beta), max(model_fit$coefficients), 
             paste("相关性:", round(cor_val, 3)), 
             adj = c(0, 1))
    }
    
    # 重置图形参数
    par(mfrow = c(1, 1))
}